name: Build and Publish to GitHubPackages

on:
  push:
    tags:
      - '**-github_pkg'

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=$(echo "${GITHUB_REF##*/}" | sed 's/-github_pkg$//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Release with gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: --no-daemon -i --no-configuration-cache publishAllPublicationsToGitHubPackagesRepository
        env:
          AC_GITHUB_ACTOR: ${{ secrets.AC_GITHUB_ACTOR }}
          AC_GITHUB_TOKEN: ${{ secrets.AC_GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
          PROJECT_VERSION: ${{ env.VERSION }}
